debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM0
frame_id: gps
dynamic_model: portable
fix_mode: auto              # Switches between 2D/3D automatically
dr_limit: 0                 # Dead reckoning limit
enable_ppp: false           # Advanced setting not supported by all devices

rate: 4                     # Measurement rate in Hz
nav_rate: 1                 # in number of measurement cycles

# uart1:
#   baudrate: 9600           # baudrate is device specific, check the device manual
#   in: 4                     # UBX
#   out: 0                    # RTCM

tmode3: 0                   # Survey-In Mode
sv_in:
  reset: false              # True: disables and re-enables survey-in (resets)
                            # False: Disables survey-in only if TMODE3 is  
                            # disabled
  min_dur: 300              # Survey-In Minimum Duration [s]
  acc_lim: 3.0              # Survey-In Accuracy Limit [m]  

dat:
  set: false                # Do not set the user configured datum

# GNSS Config, verify which GNSS are supported by your device
gnss:
  gps: true                 # (not required since it defaults to true)
  glonass: true
  beidou: false
  qzss: false
  sbas: false

inf:
  all: true                   # Whether to display INF messages

# Message subscriptions
subscribe:
  all: true                 # Subscribe to all messages
  aid:
    all: false                # ... except AID messages